name: face_box_camera
description: "A package to detect face inside defined a box or not."
version: 0.0.7
homepage: https://github.com/momyuke/face_box_camera
repository: https://github.com/momyuke/face_box_camera

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  google_mlkit_face_detection: ^0.13.1
  camera: ^0.11.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.5.1
  build_runner: ^2.4.9
  camera_platform_interface: ^2.11.0

flutter:
